name: Build and Push Docker Image

on:
  push:
    branches: [main]
    paths:
      - "go-rest-api/**"
      - "go-test-api/**"
      - "other_project_dockerfile"
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - "go-rest-api/**"
      - "go-test-api/**"
      # - "other_project_dockerfile"
  workflow_dispatch:
    inputs:
      go-api-name:
        description: "Go API to build (e.g., go-rest-api, go-test-api, or all)"
        required: false
        type: choice
        options:
          - "all"
          - "go-rest-api"
          - "go-test-api"
        default: "all"
      tag-name:
        description: "Custom tag name (optional)"
        required: false
      registry-name-dockerhub:
        description: "registry docker hub"
        required: false
        type: choice
        options:
          - "all"
          - "gh-action-dh-rest-repo"
          - "gh-action-dh-test-repo"
          # - "ns185356-first-repo"
        default: "all"
      # registry-name-edge:
      #   description: 'registry docker repo edge'
      #   required: false
      #   type: string
      #   default: 'us-east1-docker.pkg.dev/ret-edge-pltf-infra/workloads'
      push-latest:
        description: "Push the 'latest' tag (only on main)"
        required: false
        type: boolean
        default: false
      push-dh:
        description: "Push to dh registry"
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      go-rest-api-changed: ${{ steps.filter.outputs.go-rest-api-changed }}
      go-test-api-changed: ${{ steps.filter.outputs.go-test-api-changed }}
      # shared: ${{ steps.filter.outputs.shared }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            go-rest-api-changed:
              - 'go-rest-api/**'
            go-test-api-changed:
              - 'go-test-api/**'
            # shared:
            #   - 'other_project_dockerfile'

  setup-matrix:
    name: Setup build matrix
    needs: detect-changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      # ...existing code...
      - name: Set up matrix
        id: set-matrix
        run: |
          # Initialize default matrix
          MATRIX='{"include":[]}'

          echo "=== Change Detection Results ==="
          echo "Go REST API Changed: ${{ needs.detect-changes.outputs.go-rest-api-changed }}"
          echo "Go Test API Changed: ${{ needs.detect-changes.outputs.go-test-api-changed }}"
          # echo "Shared Files Changed: ${{ needs.detect-changes.outputs.shared }}"
          echo "================================"

          echo "=== Setup matrix based on inputs ===="
          GO_API_NAME="${{ github.event.inputs.go-api-name || 'all' }}"
          GO_REST_API_CHANGED="${{ needs.detect-changes.outputs.go-rest-api-changed }}"
          GO_TEST_API_CHANGED="${{ needs.detect-changes.outputs.go-test-api-changed }}"
          # SHARED_CHANGED="${{ needs.detect-changes.outputs.shared }}"


          # Default behavior: when GO_API_NAME == 'all' include both projects regardless of change detection
          if [[ "$GO_API_NAME" == "all" ]]; then
            MATRIX=$(echo "$MATRIX" | jq -c '.include += [{"go-api":"go-rest-api"},{"go-api":"go-test-api"}]')
          elif [[ "$GO_API_NAME" == "go-rest-api" ]]; then
            MATRIX=$(echo "$MATRIX" | jq -c '.include += [{"go-api":"go-rest-api"}]')
          elif [[ "$GO_API_NAME" == "go-test-api" ]]; then
            MATRIX=$(echo "$MATRIX" | jq -c '.include += [{"go-api":"go-test-api"}]')
          fi

          # Validate JSON
          echo "$MATRIX" | jq '.' > /dev/null || MATRIX='{"include":[]}'

          # Debug output
          echo "Final matrix: $MATRIX"

          # Write to outputs without indentation
          cat << EOF >> $GITHUB_OUTPUT
          matrix=$MATRIX
          EOF

          if [[ $(echo "$MATRIX" | jq '.include | length') -eq 0 ]]; then
            echo "No changes detected in selected Go APIs. Exiting."
            exit 0
          fi

  build-and-push:
    # changed: ensure this job uses the matrix produced earlier and depends on setup-matrix
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix || '{"include":[]}') }}
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show build context (debug)
        run: |
          echo "Building for matrix entry: ${{ matrix.go-api }}"
          ls -la ./${{ matrix.go-api }} || true
          if [ ! -f "./${{ matrix.go-api }}/Dockerfile" ]; then
            echo "ERROR: Dockerfile not found in ./${{ matrix.go-api }}/"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata like naming image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ matrix.go-api == 'go-rest-api' && 'ns185356/gh-action-dh-rest-repo' || '' }}
            ${{ matrix.go-api == 'go-test-api' && 'ns185356/gh-action-dh-test-repo' || '' }}
          tags: |
            # Manual tag input (if provided)
            type=raw,value=${{ inputs.tag-name }},enable=${{ inputs.tag-name != '' }}
            # Main branch gets latest
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' && inputs.tag-name == '' }}
            # Pull request gets pr-number
            type=raw,value=pr-${{ github.event.pull_request.number }},enable=${{ github.event_name == 'pull_request' && inputs.tag-name == '' }}
            # Everything else gets pr-run_number
            type=raw,value=pr-${{ github.run_number }},enable=${{ github.ref != 'refs/heads/main' && github.event_name != 'pull_request' && inputs.tag-name == '' }}
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # changed: set context to the api folder and point to that folder's Dockerfile
          context: ./${{ matrix.go-api }}
          file: ./${{ matrix.go-api }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
